---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: poll-deployment
  labels:
    app: poll
spec:
  selector:
    matchLabels:
      app: poll
  template:
    metadata:
      labels:
        app: poll
    spec:
      serviceAccount: workload-identity-sa
      containers:
        - name: poll-container
          image: epomatti/azure-failover-poll
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            periodSeconds: 10
            timeoutSeconds: 5
          env:
            - name: USE_KEYVAULT
              valueFrom:
                configMapKeyRef:
                  name: solution-configmap
                  key: USE_KEYVAULT
            - name: USE_TOKEN_CREDENTIAL
              valueFrom:
                configMapKeyRef:
                  name: solution-configmap
                  key: USE_TOKEN_CREDENTIAL
            - name: KEYVAULT_URL
              valueFrom:
                configMapKeyRef:
                  name: solution-configmap
                  key: KEYVAULT_URL
                  optional: true
            - name: COSMOSDB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: solution-secrets
                  key: COSMOSDB_CONNECTION_STRING
                  optional: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-deployment
  labels:
    app: vote
spec:
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      serviceAccount: workload-identity-sa
      containers:
        - name: vote-container
          image: epomatti/azure-failover-vote
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            periodSeconds: 10
            timeoutSeconds: 5
          env:
            - name: POLL_API
              value: http://poll-service:30000
            - name: USE_KEYVAULT
              valueFrom:
                configMapKeyRef:
                  name: solution-configmap
                  key: USE_KEYVAULT
            - name: USE_TOKEN_CREDENTIAL
              valueFrom:
                configMapKeyRef:
                  name: solution-configmap
                  key: USE_TOKEN_CREDENTIAL
            - name: KEYVAULT_URL
              valueFrom:
                configMapKeyRef:
                  name: solution-configmap
                  key: KEYVAULT_URL
                  optional: true
            - name: COSMOSDB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: solution-secrets
                  key: COSMOSDB_CONNECTION_STRING
                  optional: true
---
apiVersion: v1
kind: Service
metadata:
  name: poll-service
spec:
  selector:
    app: poll
  ports:
    - protocol: TCP
      port: 30000
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: vote-service
spec:
  selector:
    app: vote
  ports:
    - protocol: TCP
      port: 31000
      targetPort: 8080
