version: "3.9"
services:
  poll:
    build: ./poll/
    ports:
      - "4000:8080"
    volumes:
      - .:/code
    environment:
      MONGODB_CONNECTION_STRING: mongodb://microservices_mongo_1:27017
    depends_on:
      - mongo
  vote:
    build: ./vote/
    ports:
      - "5000:8080"
    volumes:
      - .:/code
    environment:
      MONGODB_CONNECTION_STRING: mongodb://microservices_mongo_1:27017
      POLL_API: http://microservices_poll_1:8080
    depends_on:
      - mongo
      - poll
  mongo:
    image: "mongo"